// Generates admin_keys.circom with 100 BabyJubJub public keys (k=1..100)
// BabyJubJub twisted Edwards: a*x^2 + y^2 = 1 + d*x^2*y^2
// Field: bn128 scalar field

const p = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const a = 168700n;
const d = 168696n;
const Gx = 5299619240641551281634865583518297030282874472190772894086521144482721001553n;
const Gy = 16950150798460657717958625567821834550301663161624707787222815936182638968203n;

function mod(x) {
    return ((x % p) + p) % p;
}

function inv(x) {
    // Extended Euclidean algorithm
    let [old_r, r] = [x, p];
    let [old_s, s] = [1n, 0n];
    while (r !== 0n) {
        const q = old_r / r;
        [old_r, r] = [r, old_r - q * r];
        [old_s, s] = [s, old_s - q * s];
    }
    return mod(old_s);
}

function addPoints(p1, p2) {
    const [x1, y1] = p1;
    const [x2, y2] = p2;
    const x1x2 = mod(x1 * x2);
    const y1y2 = mod(y1 * y2);
    const dx1x2y1y2 = mod(d * x1x2 % p * mod(y1 * y2) % p);
    const x3 = mod(mod(x1 * y2 + y1 * x2) * inv(mod(1n + dx1x2y1y2)));
    const y3 = mod(mod(y1y2 - a * x1x2) * inv(mod(1n - dx1x2y1y2)));
    return [x3, y3];
}

function scalarMul(k, point) {
    let result = null; // point at infinity
    let addend = point;
    while (k > 0n) {
        if (k & 1n) {
            result = result === null ? addend : addPoints(result, addend);
        }
        addend = addPoints(addend, addend);
        k >>= 1n;
    }
    return result;
}

const G = [Gx, Gy];
const NUM_ADMINS = 100;
const keys = [];
for (let i = 1; i <= NUM_ADMINS; i++) {
    keys.push(scalarMul(BigInt(i), G));
}

// Verify against known values from eip7503-extension.circom
const known = [
    [5299619240641551281634865583518297030282874472190772894086521144482721001553n, 16950150798460657717958625567821834550301663161624707787222815936182638968203n],
    [10031262171927540148667355526369034398030886437092045105752248699557385197826n, 633281375905621697187330766174974863687049529291089048651929454608812697683n],
    [2763488322167937039616325905516046217694264098671987087929565332380420898366n, 15305195750036305661220525648961313310481046260814497672243197092298550508693n],
    [12252886604826192316928789929706397349846234911198931249025449955069330867144n, 1286140751908834028607023759717162073146610688084909004843365841635476459484n],
    [11480966271046430430613841218147196773252373073876138147006741179837832100836n, 15148236048131954717802795400425086368006776860859772698778589175317365693546n],
    [10483991165196995731760716870725509190315033255344071753161464961897900552628n, 16822899191463256771813724222715007505997804748105685077895991386716774358231n],
    [20092560661213339045022877747484245238324772779820628739268223482659246842641n, 12112450042127193446189577552007703839818242727902437791835414514847797088033n],
    [7582035475627193640797276505418002166691739036475590846121162698650004832581n, 7801528930831391612913542953849263092120765287178679640990215688947513841260n],
    [4705897243203718691035604313913899717760209962238015362153877735592901317263n, 11533909001000295577818857040682494493436124051895563619976413559559984357704n],
];
let ok = true;
for (let i = 0; i < known.length; i++) {
    if (keys[i][0] !== known[i][0] || keys[i][1] !== known[i][1]) {
        console.error(`Mismatch at k=${i+1}: got (${keys[i][0]}, ${keys[i][1]})`);
        ok = false;
    }
}
if (!ok) process.exit(1);
console.log("Verification passed for keys 1-9.");

// Emit circom file
const lines = [
    `pragma circom 2.0.0;`,
    ``,
    `// Auto-generated by gen_admin_keys.js`,
    `// Admin public keys: i-th key = i * BabyJubJub_Base8 (i = 1..${NUM_ADMINS})`,
    ``,
    `template AdminKeys() {`,
    `    var NUM_ADMINS = ${NUM_ADMINS};`,
    `    signal output PKX[${NUM_ADMINS}];`,
    `    signal output PKY[${NUM_ADMINS}];`,
    ``,
];
for (let i = 0; i < NUM_ADMINS; i++) {
    lines.push(`    PKX[${i}] <== ${keys[i][0]};`);
    lines.push(`    PKY[${i}] <== ${keys[i][1]};`);
}
lines.push(`}`);
lines.push(``);

const fs = require('fs');
fs.writeFileSync(__dirname + '/utils/admin_keys.circom', lines.join('\n'));
console.log(`Wrote utils/admin_keys.circom with ${NUM_ADMINS} admin keys.`);
